# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/zynq_test/project_2/project_2.srcs/sources_1/ip/fp_accumulator/fp_accumulator.xci
# IP: The module: 'fp_accumulator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zynq_test/project_2/project_2.srcs/sources_1/ip/fp_accumulator/fp_accumulator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_accumulator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/zynq_test/project_2/project_2.srcs/sources_1/ip/fp_accumulator/fp_accumulator.xci
# IP: The module: 'fp_accumulator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zynq_test/project_2/project_2.srcs/sources_1/ip/fp_accumulator/fp_accumulator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_accumulator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
