# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/zynq_test/project_2/project_2.srcs/sources_1/bd/mpram/ip/mpram_s00_data_fifo_0/mpram_s00_data_fifo_0.xci
# IP: The module: 'mpram_s00_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zynq_test/project_2/project_2.srcs/sources_1/bd/mpram/ip/mpram_s00_data_fifo_0/mpram_s00_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpram_s00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/zynq_test/project_2/project_2.srcs/sources_1/bd/mpram/ip/mpram_s00_data_fifo_0/mpram_s00_data_fifo_0.xci
# IP: The module: 'mpram_s00_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zynq_test/project_2/project_2.srcs/sources_1/bd/mpram/ip/mpram_s00_data_fifo_0/mpram_s00_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpram_s00_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
